// Code generated by SQLBoiler 3.6.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

// This test suite runs each operation test in parallel.
// Example, if your database has 3 tables, the suite will run:
// table1, table2 and table3 Delete in parallel
// table1, table2 and table3 Insert in parallel, and so forth.
// It does NOT run each operation group in parallel.
// Separating the tests thusly grants avoidance of Postgres deadlocks.
func TestParent(t *testing.T) {
	t.Run("Orders", testOrders)
	t.Run("OrderItems", testOrderItems)
}

func TestDelete(t *testing.T) {
	t.Run("Orders", testOrdersDelete)
	t.Run("OrderItems", testOrderItemsDelete)
}

func TestQueryDeleteAll(t *testing.T) {
	t.Run("Orders", testOrdersQueryDeleteAll)
	t.Run("OrderItems", testOrderItemsQueryDeleteAll)
}

func TestSliceDeleteAll(t *testing.T) {
	t.Run("Orders", testOrdersSliceDeleteAll)
	t.Run("OrderItems", testOrderItemsSliceDeleteAll)
}

func TestExists(t *testing.T) {
	t.Run("Orders", testOrdersExists)
	t.Run("OrderItems", testOrderItemsExists)
}

func TestFind(t *testing.T) {
	t.Run("Orders", testOrdersFind)
	t.Run("OrderItems", testOrderItemsFind)
}

func TestBind(t *testing.T) {
	t.Run("Orders", testOrdersBind)
	t.Run("OrderItems", testOrderItemsBind)
}

func TestOne(t *testing.T) {
	t.Run("Orders", testOrdersOne)
	t.Run("OrderItems", testOrderItemsOne)
}

func TestAll(t *testing.T) {
	t.Run("Orders", testOrdersAll)
	t.Run("OrderItems", testOrderItemsAll)
}

func TestCount(t *testing.T) {
	t.Run("Orders", testOrdersCount)
	t.Run("OrderItems", testOrderItemsCount)
}

func TestHooks(t *testing.T) {
	t.Run("Orders", testOrdersHooks)
	t.Run("OrderItems", testOrderItemsHooks)
}

func TestInsert(t *testing.T) {
	t.Run("Orders", testOrdersInsert)
	t.Run("Orders", testOrdersInsertWhitelist)
	t.Run("OrderItems", testOrderItemsInsert)
	t.Run("OrderItems", testOrderItemsInsertWhitelist)
}

// TestToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestToOne(t *testing.T) {}

// TestOneToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOne(t *testing.T) {}

// TestToMany tests cannot be run in parallel
// or deadlocks can occur.
func TestToMany(t *testing.T) {}

// TestToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneSet(t *testing.T) {}

// TestToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneRemove(t *testing.T) {}

// TestOneToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneSet(t *testing.T) {}

// TestOneToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneRemove(t *testing.T) {}

// TestToManyAdd tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyAdd(t *testing.T) {}

// TestToManySet tests cannot be run in parallel
// or deadlocks can occur.
func TestToManySet(t *testing.T) {}

// TestToManyRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyRemove(t *testing.T) {}

func TestReload(t *testing.T) {
	t.Run("Orders", testOrdersReload)
	t.Run("OrderItems", testOrderItemsReload)
}

func TestReloadAll(t *testing.T) {
	t.Run("Orders", testOrdersReloadAll)
	t.Run("OrderItems", testOrderItemsReloadAll)
}

func TestSelect(t *testing.T) {
	t.Run("Orders", testOrdersSelect)
	t.Run("OrderItems", testOrderItemsSelect)
}

func TestUpdate(t *testing.T) {
	t.Run("Orders", testOrdersUpdate)
	t.Run("OrderItems", testOrderItemsUpdate)
}

func TestSliceUpdateAll(t *testing.T) {
	t.Run("Orders", testOrdersSliceUpdateAll)
	t.Run("OrderItems", testOrderItemsSliceUpdateAll)
}
