// Code generated by SQLBoiler 3.6.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/randomize"
	"github.com/volatiletech/sqlboiler/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testOrderItems(t *testing.T) {
	t.Parallel()

	query := OrderItems()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testOrderItemsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OrderItem{}
	if err = randomize.Struct(seed, o, orderItemDBTypes, true, orderItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OrderItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := OrderItems().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testOrderItemsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OrderItem{}
	if err = randomize.Struct(seed, o, orderItemDBTypes, true, orderItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OrderItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := OrderItems().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := OrderItems().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testOrderItemsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OrderItem{}
	if err = randomize.Struct(seed, o, orderItemDBTypes, true, orderItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OrderItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := OrderItemSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := OrderItems().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testOrderItemsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OrderItem{}
	if err = randomize.Struct(seed, o, orderItemDBTypes, true, orderItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OrderItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := OrderItemExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if OrderItem exists: %s", err)
	}
	if !e {
		t.Errorf("Expected OrderItemExists to return true, but got false.")
	}
}

func testOrderItemsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OrderItem{}
	if err = randomize.Struct(seed, o, orderItemDBTypes, true, orderItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OrderItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	orderItemFound, err := FindOrderItem(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if orderItemFound == nil {
		t.Error("want a record, got nil")
	}
}

func testOrderItemsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OrderItem{}
	if err = randomize.Struct(seed, o, orderItemDBTypes, true, orderItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OrderItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = OrderItems().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testOrderItemsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OrderItem{}
	if err = randomize.Struct(seed, o, orderItemDBTypes, true, orderItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OrderItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := OrderItems().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testOrderItemsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	orderItemOne := &OrderItem{}
	orderItemTwo := &OrderItem{}
	if err = randomize.Struct(seed, orderItemOne, orderItemDBTypes, false, orderItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OrderItem struct: %s", err)
	}
	if err = randomize.Struct(seed, orderItemTwo, orderItemDBTypes, false, orderItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OrderItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = orderItemOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = orderItemTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := OrderItems().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testOrderItemsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	orderItemOne := &OrderItem{}
	orderItemTwo := &OrderItem{}
	if err = randomize.Struct(seed, orderItemOne, orderItemDBTypes, false, orderItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OrderItem struct: %s", err)
	}
	if err = randomize.Struct(seed, orderItemTwo, orderItemDBTypes, false, orderItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OrderItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = orderItemOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = orderItemTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := OrderItems().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func orderItemBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *OrderItem) error {
	*o = OrderItem{}
	return nil
}

func orderItemAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *OrderItem) error {
	*o = OrderItem{}
	return nil
}

func orderItemAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *OrderItem) error {
	*o = OrderItem{}
	return nil
}

func orderItemBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *OrderItem) error {
	*o = OrderItem{}
	return nil
}

func orderItemAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *OrderItem) error {
	*o = OrderItem{}
	return nil
}

func orderItemBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *OrderItem) error {
	*o = OrderItem{}
	return nil
}

func orderItemAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *OrderItem) error {
	*o = OrderItem{}
	return nil
}

func orderItemBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *OrderItem) error {
	*o = OrderItem{}
	return nil
}

func orderItemAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *OrderItem) error {
	*o = OrderItem{}
	return nil
}

func testOrderItemsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &OrderItem{}
	o := &OrderItem{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, orderItemDBTypes, false); err != nil {
		t.Errorf("Unable to randomize OrderItem object: %s", err)
	}

	AddOrderItemHook(boil.BeforeInsertHook, orderItemBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	orderItemBeforeInsertHooks = []OrderItemHook{}

	AddOrderItemHook(boil.AfterInsertHook, orderItemAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	orderItemAfterInsertHooks = []OrderItemHook{}

	AddOrderItemHook(boil.AfterSelectHook, orderItemAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	orderItemAfterSelectHooks = []OrderItemHook{}

	AddOrderItemHook(boil.BeforeUpdateHook, orderItemBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	orderItemBeforeUpdateHooks = []OrderItemHook{}

	AddOrderItemHook(boil.AfterUpdateHook, orderItemAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	orderItemAfterUpdateHooks = []OrderItemHook{}

	AddOrderItemHook(boil.BeforeDeleteHook, orderItemBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	orderItemBeforeDeleteHooks = []OrderItemHook{}

	AddOrderItemHook(boil.AfterDeleteHook, orderItemAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	orderItemAfterDeleteHooks = []OrderItemHook{}

	AddOrderItemHook(boil.BeforeUpsertHook, orderItemBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	orderItemBeforeUpsertHooks = []OrderItemHook{}

	AddOrderItemHook(boil.AfterUpsertHook, orderItemAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	orderItemAfterUpsertHooks = []OrderItemHook{}
}

func testOrderItemsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OrderItem{}
	if err = randomize.Struct(seed, o, orderItemDBTypes, true, orderItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OrderItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := OrderItems().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testOrderItemsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OrderItem{}
	if err = randomize.Struct(seed, o, orderItemDBTypes, true); err != nil {
		t.Errorf("Unable to randomize OrderItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(orderItemColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := OrderItems().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testOrderItemsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OrderItem{}
	if err = randomize.Struct(seed, o, orderItemDBTypes, true, orderItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OrderItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testOrderItemsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OrderItem{}
	if err = randomize.Struct(seed, o, orderItemDBTypes, true, orderItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OrderItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := OrderItemSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testOrderItemsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OrderItem{}
	if err = randomize.Struct(seed, o, orderItemDBTypes, true, orderItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OrderItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := OrderItems().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	orderItemDBTypes = map[string]string{`ID`: `int`, `OrderID`: `int`, `SID`: `int`, `UserID`: `int`, `GID`: `int`, `Name`: `varchar`, `Num`: `int`, `Price`: `int`, `IsDeleted`: `int`, `Status`: `tinyint`, `CreatedAt`: `int`, `UpdatedAt`: `int`, `DeletedAt`: `int`}
	_                = bytes.MinRead
)

func testOrderItemsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(orderItemPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(orderItemAllColumns) == len(orderItemPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &OrderItem{}
	if err = randomize.Struct(seed, o, orderItemDBTypes, true, orderItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OrderItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := OrderItems().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, orderItemDBTypes, true, orderItemPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize OrderItem struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testOrderItemsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(orderItemAllColumns) == len(orderItemPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &OrderItem{}
	if err = randomize.Struct(seed, o, orderItemDBTypes, true, orderItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OrderItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := OrderItems().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, orderItemDBTypes, true, orderItemPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize OrderItem struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(orderItemAllColumns, orderItemPrimaryKeyColumns) {
		fields = orderItemAllColumns
	} else {
		fields = strmangle.SetComplement(
			orderItemAllColumns,
			orderItemPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := OrderItemSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testOrderItemsUpsert(t *testing.T) {
	t.Parallel()

	if len(orderItemAllColumns) == len(orderItemPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}
	if len(mySQLOrderItemUniqueColumns) == 0 {
		t.Skip("Skipping table with no unique columns to conflict on")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := OrderItem{}
	if err = randomize.Struct(seed, &o, orderItemDBTypes, false); err != nil {
		t.Errorf("Unable to randomize OrderItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert OrderItem: %s", err)
	}

	count, err := OrderItems().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, orderItemDBTypes, false, orderItemPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize OrderItem struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert OrderItem: %s", err)
	}

	count, err = OrderItems().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
