// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package wire

import (
	"github.com/yuchanns/gobyexample/grpc-app/app"
	"github.com/yuchanns/gobyexample/grpc-app/domain/greeter"
	"github.com/yuchanns/gobyexample/grpc-app/infra/repository/sqlite3"
	"github.com/yuchanns/gobyexample/grpc-app/proto/greeter"
	"github.com/yuchanns/gobyexample/grpc-app/server"
)

// Injectors from wire.go:

func InitializeGreeterServer() hello_world.GreeterServer {
	iGreeterRepo := sqlite3.NewGreeterRepo()
	iDomSvc := greeter.NewDomSvc(iGreeterRepo)
	greeterSvc := app.NewGreeterSvc(iDomSvc)
	greeterServer := server.NewGreeterServer(greeterSvc)
	return greeterServer
}
