// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package wire

// Injectors from wire.go:

func InitialEvent() *Event {
	message := NewMessage()
	greeter := NewGreeter(message)
	event := NewEvent(greeter)
	return event
}
