// Code generated by SQLBoiler 3.6.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package boiler

var TableNames = struct {
	Articles   string
	Categories string
	Markdown   string
	TagArticle string
	Tags       string
}{
	Articles:   "articles",
	Categories: "categories",
	Markdown:   "markdown",
	TagArticle: "tag_article",
	Tags:       "tags",
}
